runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  secure: always

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /apple-touch-icon-precomposed.png
  static_files: static/img/apple-touch-icon-precomposed.png
  upload: static/img/apple-touch-icon-precomposed.png
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: _go_app
  login: required
  secure: always

